main: artdev.App
name: TownagePlugin
version: 1.0.1
commands:
  Trange:
    description: 设置一个范围，不懂问AaronRobert
    usage: /Trange [build/add/ls/rm] (rangeName:string) [(x1:int) (y1:int) (z1:int) (x2:int) (y2:int) (z1:int)]
  Tstage:
    description: 设置一个STAGE，不懂问AaronRobert
    usage: /Tstage [build/add/ls/rm] (stageName:string) (internal:int) [(x:int) (y:int) (z:int)] (rangeName,...:Range)